# Generated by Django 5.1.7 on 2025-05-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postventa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="pedido_completado",
            field=models.BooleanField(default=False),
        ),
    ]
