# Generated by Django 5.1.7 on 2025-05-30 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketEcommerce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=20)),
                ("direccion", models.CharField(max_length=255)),
                ("comuna", models.CharField(max_length=100)),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[("pagado", "Pagado"), ("pendiente", "Pendiente")],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "estado_envio",
                    models.CharField(
                        choices=[
                            ("recolectando productos", "Recolectando productos"),
                            ("productos recolectados", "Productos recolectados"),
                            ("producto entregado", "Producto entregado"),
                        ],
                        default="recolectando productos",
                        max_length=30,
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(blank=True, null=True, upload_to="comprobantes/"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductoTicketEcommerce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=255)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="carrito_ecommerce.ticketecommerce",
                    ),
                ),
            ],
        ),
    ]
