# Generated by Django 5.1.7 on 2025-05-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrito_ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketecommerce",
            name="metodo_pago",
            field=models.CharField(
                choices=[("paypal", "PayPal"), ("transferencia", "Transferencia")],
                default="paypal",
                max_length=20,
            ),
        ),
    ]
