# Generated by Django 5.1.7 on 2025-05-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrito_ecommerce", "0003_ticketecommerce_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketecommerce",
            name="email_usuario",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
