# Generated by Django 5.1.7 on 2025-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrito_ecommerce", "0004_ticketecommerce_email_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketecommerce",
            name="es_carrito",
            field=models.BooleanField(default=True),
        ),
    ]
