# Generated by Django 5.1.7 on 2025-05-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='creado_en',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='carrito',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cantidad',
            new_name='quantity',
        ),
    ]
