# Generated by Django 5.1.7 on 2025-06-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("cliente", "Cliente"),
                    ("contador", "Contador"),
                    ("bodeguero", "Bodeguero"),
                    ("repartidor", "Repartidor"),
                    ("cajero", "Cajero"),
                    ("admin", "Administrador"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
