# Generated by Django 5.1.7 on 2025-05-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.IntegerField(default=0),
        ),
    ]
