# Generated by Django 5.1.7 on 2025-05-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
    ]
